version: '3.3'
services:
  self-hosted-runner:
    image: nvidia/cuda:11.2.1-cudnn8-runtime-ubuntu18.04
    volumes:
      - ./bin/:/root/bin
      - ./config.sh:/root/config.sh
      - ./_diag:/root/_diag
      - ./env.sh:/root/env.sh
      - ./run.sh:/root/run.sh
      - ./svc.sh:/root/svc.sh
      - ./_work:/root/_work
      - ./externals:/root/externals
      - ./create-and-start.sh:/root/create-and-start.sh
    entrypoint: /root/create-and-start.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count:  2
              capabilities:
                - gpu
