name: Update dependencies linux
runs:
  using: composite
  steps:
    - name: Update dependencies linux
      shell: bash
      run: |
              SCL_ENABLE="devtoolset-7"
              CENTOS_VERSION=$(rpm --eval '%{centos_ver}')
              if [[ "$CENTOS_VERSION" == "6" ]]; then
                find /etc/yum.repos.d/ -name *.repo | xargs -i sed -i 's/mirror\.centos\.org\/centos/vault.centos.org/g;s/$releasever/6.10/g;s/mirrorlist/#mirrorlist/g;s/#baseurl/baseurl/g' {}
                SCL_ENABLE="devtoolset-7 rh-python36 python27"
              fi
              yum -y update
              yum -y install centos-release-scl-rh epel-release gnupg2
              if [[ "$CENTOS_VERSION" == "6" ]]; then
                sed -i 's/mirror\.centos\.org\/centos/vault.centos.org/g;s/6\/sclo/6.10\/sclo/g;s/mirrorlist/#mirrorlist/g;s/#baseurl/baseurl/g' /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
              fi
              yum -y install $SCL_ENABLE rh-java-common-ant boost-devel ccache clang gcc-c++ gcc-gfortran java-1.8.0-openjdk-devel ant python python36-devel python36-pip swig file which wget unzip tar bzip2 gzip xz patch autoconf-archive automake make libtool bison flex perl nasm alsa-lib-devel freeglut-devel gtk2-devel libusb-devel libusb1-devel curl-devel expat-devel gettext-devel openssl-devel bzip2-devel zlib-devel SDL-devel libva-devel libxkbcommon-devel libxkbcommon-x11-devel xcb-util* fontconfig-devel libffi-devel ragel ocl-icd-devel GeoIP-devel pcre-devel ssdeep-devel yajl-devel libgomp pinentry zlib-devel ca-certificates
              # https://gcc.gnu.org/legacy-ml/gcc-patches/2018-01/msg01962.html
              sed -i 's/_mm512_abs_pd (__m512 __A)/_mm512_abs_pd (__m512d __A)/g' /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/avx512fintrin.h
              source scl_source enable $SCL_ENABLE || true
              echo "SCL_ENABLE=$SCL_ENABLE" >> $GITHUB_ENV
              # Without the line below, gpg2 might fail to create / import secret keys !!!
              gpg --version
              killall gpg-agent || true
              GNUPGHOME=/root/.gnupg
              echo "GNUPGHOME=/root/.gnupg" >> "$GITHUB_ENV"
              gpg-agent --homedir /root/.gnupg --daemon --use-standard-socket --yes
              echo 'pinentry-program /usr/bin/pinentry-curses' | tee -a /root/.gnupg/gpg-agent.conf
              #gpg-connect-agent reloadagent /bye
              env
