name: Update dependencies linux
runs:
  using: composite
  steps:
    - name: Update dependencies linux
      shell: bash
      run: |
              SCL_ENABLE="devtoolset-7"
              CENTOS_VERSION=$(rpm --eval '%{centos_ver}')
              if [[ "$CENTOS_VERSION" == "6" ]]; then
                find /etc/yum.repos.d/ -name *.repo | xargs -i sed -i 's/mirror\.centos\.org\/centos/vault.centos.org/g;s/$releasever/6.10/g;s/mirrorlist/#mirrorlist/g;s/#baseurl/baseurl/g' {}
                SCL_ENABLE="devtoolset-7 rh-python36 python27"
              fi
              yum -y update
              yum -y install centos-release-scl-rh epel-release
              if [[ "$CENTOS_VERSION" == "6" ]]; then
                sed -i 's/mirror\.centos\.org\/centos/vault.centos.org/g;s/6\/sclo/6.10\/sclo/g;s/mirrorlist/#mirrorlist/g;s/#baseurl/baseurl/g' /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
              fi

              yum -y install $SCL_ENABLE rh-java-common-ant boost-devel ccache clang gcc-c++ gcc-gfortran java-1.8.0-openjdk-devel ant python python36-devel python36-pip swig file which wget unzip tar bzip2 gzip xz patch autoconf-archive automake make libtool bison flex perl nasm alsa-lib-devel freeglut-devel gtk2-devel libusb-devel libusb1-devel curl-devel expat-devel gettext-devel openssl-devel bzip2-devel zlib-devel SDL-devel libva-devel libxkbcommon-devel libxkbcommon-x11-devel xcb-util* fontconfig-devel libffi-devel ragel ocl-icd-devel GeoIP-devel pcre-devel ssdeep-devel yajl-devel libgomp pinentry zlib-devel ca-certificates
              wget https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.36.tar.bz2
              tar jxf libgpg-error-1.36.tar.bz2
              cd libgpg-error-1.36
              ./configure --prefix=/usr/local
              make
              make install
              cd ..
              wget https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.4.tar.bz2
              tar jxf libgcrypt-1.8.4.tar.bz2
              cd libgcrypt-1.8.4
              ./configure --prefix=/usr/local
              make
              ls
              make install
              ln -s /usr/local/lib/libgcrypt.so.20 /usr/lib/libgcrypt.so.20
              cd ..
              wget https://www.gnupg.org/ftp/gcrypt/libksba/libksba-1.3.5.tar.bz2
              tar jxf libksba-1.3.5.tar.bz2
              cd libksba-1.3.5
              ./configure --prefix=/usr/local
              make
              make install
              cd ..
              wget https://www.gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.3.tar.bz2
              tar jxf libassuan-2.5.3.tar.bz2
              cd libassuan-2.5.3
              ./configure --prefix=/usr/local
              make
              make install
              cd ..
              wget https://www.gnupg.org/ftp/gcrypt/ntbtls/ntbtls-0.1.2.tar.bz2
              tar jxf ntbtls-0.1.2.tar.bz2
              cd ntbtls-0.1.2
              ./configure --prefix=/usr/local
              make
              make install
              cd ..
              wget https://www.gnupg.org/ftp/gcrypt/npth/npth-1.6.tar.bz2
              tar jxf npth-1.6.tar.bz2
              cd npth-1.6
              ./configure --prefix=/usr/local
              make
              make install
              cd ..
              echo 'include /usr/local/lib/' >> /etc/ld.so.conf
              ldconfig -v
              wget https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.17.tar.bz2
              tar jxf gnupg-2.2.17.tar.bz2
              cd gnupg-2.2.17/
              ./configure --prefix=/usr/local
              make
              make install
              cd ..
              # https://gcc.gnu.org/legacy-ml/gcc-patches/2018-01/msg01962.html
              sed -i 's/_mm512_abs_pd (__m512 __A)/_mm512_abs_pd (__m512d __A)/g' /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/include/avx512fintrin.h
              source scl_source enable $SCL_ENABLE || true
              echo "SCL_ENABLE=$SCL_ENABLE" >> $GITHUB_ENV
              # Without the line below, gpg2 might fail to create / import secret keys !!!
              gpg --version
              killall gpg-agent || true
              GNUPGHOME=/root/.gnupg
              echo "GNUPGHOME=/root/.gnupg" >> "$GITHUB_ENV"
              gpg-agent --homedir /root/.gnupg --daemon --use-standard-socket
              echo "--yes --no-tty --batch -v --default-key ${GPG_KEY}" >> /root/.gnupg/options
              echo 'pinentry-program /usr/bin/pinentry-curses --allow-loopback-pinentry --debug-all' >>  /root/.gnupg/gpg-agent.conf
              #gpg-connect-agent reloadagent /bye
              env
