on:
  push:
jobs:
  android-x86_64:
    runs-on: self-hosted
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r22
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build on linux-x86_64
        env:
          ANDROID_NDK: "/opt/hostedcache/ndk/r22/x64"
        run: |
          echo "Verifying programs on path. Path is $PATH"
          echo "Path post update is $PATH. Maven is at `which mvn` cmake is at `which cmake` protoc is at `which protoc`"
          mvn --version
          cmake --version
          protoc --version
          clang --version
          wget -O android-x86_64.properties https://raw.githubusercontent.com/bytedeco/javacpp/master/src/main/resources/org/bytedeco/javacpp/properties/android-x86_64.properties
          echo "Building android with NDK ${ANDROID_NDK}"
          mvn  -Pgithub -pl ":nd4j-native,:libnd4j" --also-make  \
          -Djavacpp.platform=android-x86_64  -javacpp.platform.includepath="${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/11.0.5/include/:${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/" -Djavacpp.platform.root=${ANDROID_NDK} \
          -Djavacpp.platform.sysroot=${ANDROID_NDK} -Dlibnd4j.platform=android-x86_64 -Dlibnd4j.chip=cpu \
          --batch-mode deploy -DskipTests


