on:
  push:
jobs:
  android-x86_64:
    runs-on: self-hosted
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r18b
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build on linux-x86_64
        env:
          ANDROID_NDK: "/opt/hostedcache/ndk/r18b/x64"
          OPENBLAS_PATH: "/opt/openblas/"
          LIBND4J_HOME: "${GITHUB_WORKSPACE}/libnd4j"
        run: |
          echo "Verifying programs on path. Path is $PATH"
          echo "Path post update is $PATH. Maven is at `which mvn` cmake is at `which cmake` protoc is at `which protoc`"
          mvn --version
          cmake --version
          protoc --version
          clang --version
          mvn  -X -Dorg.bytedeco.javacpp.logger.debug=true -Pgithub -pl ":nd4j-native,:libnd4j" --also-make  \
          -Djavacpp.platform=android-x86_64  \
          -Dlibnd4j.platform=android-x86_64 -Dlibnd4j.chip=cpu \
          --batch-mode clean deploy -DskipTests


