on:
  push:
jobs:
  android-x86_64:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r22
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-protobuf-linux
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build on linux-x86_64
        env:
          ANDROID_NDK: "/opt/hostedtoolcache/ndk/r22/x64"
          GNUMAKEFLAGS: "-j1"
          MAKEFLAGS: "-j1"
          MAKEOPTS: "--jobs=1 --load-average=1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Verifying programs on path. Path is $PATH"
          echo "Path post update is $PATH. Maven is at `which mvn` cmake is at `which cmake` protoc is at `which protoc`"
          mvn --version
          cmake --version
          protoc --version
          clang --version
          sudo apt-get autoremove
          sudo apt-get clean
          echo "Building android with NDK ${ANDROID_NDK}"
          mvn  -Pgithub -pl ":nd4j-native,:libnd4j" --also-make -Djavacpp.platform=android-x86_64 -Djavacpp.platform.root="${ANDROID_NDK}"  -Dlibnd4j.platform=android-x86_64 -Dlibnd4j.chip=cpu --batch-mode deploy -DskipTests


