on:
  push:
jobs:
  
  windows-x86_64:
    runs-on: windows-2019
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: ./.github/actions/msys2-base-setup
      - name: Run windows cpu build
        shell: cmd
        run: |
          set MSYSTEM=MINGW64
          set "PATH=C:\msys64\usr\bin;%PATH%"
          mvn -Djavacpp.platform=windows-x86_64  -pl ":nd4j-native,:libnd4j" --also-make -Dlibnd4j.platform=windows-x86_64  -Dlibnd4j.chip=cpu clean install -DskipTests
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn -Pgithub -Djavacpp.parser.skip=true  -pl ":nd4j-native,:libnd4j" -DskipTests --batch-mode deploy
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
