on:
  push:
jobs:
  #Note: no -pl here because we publish everything from this branch and use this as the basis for all uploads.
  linux-x86_64:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-protobuf-linux
      - uses: ./.github/actions/install-arm-cross-compile
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build on  linux-x86_64
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RPI_BIN: /opt/raspberrypi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf
          RPI_HOME: /opt/raspberrypi
        run: |
          mvn --version
          cmake --version
          protoc --version
          sudo apt-get autoremove
          sudo apt-get clean
          export CROSS_COMPILE=aarch64-linux-gnu
          export PATH="/opt/raspberrypi/tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin:${PATH}"
          mvn -Pgithub  -pl ":nd4j-native,:libnd4j" --also-make   -Dlibnd4j.platform=linux-arm64 -Djavacpp.platform=linux-arm64 -Dlibnd4j.chip=cpu -Pcpu --batch-mode deploy -DskipTests


