on:
  push:
jobs:
  #Note: no -pl here because we publish everything from this branch and use this as the basis for all uploads.
  linux-arm64:
    runs-on: ubuntu-18.04
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-protobuf-linux
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
            java-version: 1.8
      - name: Build on  linux-arm64
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          DEPLOY: 1
          BUILD_USING_MAVEN: 1
          TARGET_OS: linux
          CURRENT_TARGET: arm64
        run: |
           mvn --version
           cmake --version
           protoc --version
           ${GITHUB_WORKSPACE}/libnd4j/pi_build.sh


