on:
  push:
jobs:
  #Note: no -pl here because we publish everything from this branch and use this as the basis for all uploads.
  linux-arm64:
    runs-on: self-hosted
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
      - name: Build on  linux-x86_64
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           mvn --version
           cmake --version
           protoc --version
           export BUILD_USING_MAVEN=1
           export CURRENT_TARGET=arm64
           export TARGET_OS=linux
           export DEPLOY=1
           ${GITHUB_WORKSPACE}/libnd4j/pi_build.sh


