on:
  schedule:
    - cron: "0 */12 * * *"
jobs:
  android-x86_64:
    runs-on: ubuntu-18.04
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r18b
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-protobuf-linux
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: sonatype-nexus-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.SONATYPE_GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Build on linux-x86_64
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
          LIBND4J_HOME: "${GITHUB_WORKSPACE}/libnd4j"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USER_1 }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_USER1_PASS }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.PACKAGES_GPG_PASS }}
        run: |
          echo "Verifying programs on path. Path is $PATH"
          echo "Path post update is $PATH. Maven is at `which mvn` cmake is at `which cmake` protoc is at `which protoc`"
          mvn --version
          cmake --version
          protoc --version
          clang --version
          mvn  -X -Dorg.bytedeco.javacpp.logger.debug=true -Possrh -pl ":nd4j-native,:libnd4j" --also-make  \
          -Djavacpp.platform=android-x86_64  \
          -Dlibnd4j.platform=android-x86_64 -Dlibnd4j.chip=cpu \
          --batch-mode clean deploy -DskipTests


