on:
 push:
jobs:
  linux-x86_64:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-protobuf-linux
      - name: Buildon  linux-x86_64
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
              mvn --version
              cmake --version
              protoc --version
              mvn  -Dlibnd4j.chip=cpu clean install -DskipTests

  linux-x86_64-cuda_11-0:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: konduitai/cuda-install/.github/actions/install-cuda-ubuntu@master
        env:
          cuda: 11.0.167
          GCC: 9
      - uses: ./.github/actions/install-protobuf-linux
      - name: Build cuda
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
              mvn --version
              cmake --version
              protoc --version
              mvn -Dlibnd4j.chip=cuda clean install -DskipTests

  linux-x86_64-cuda-11-2:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: konduitai/cuda-install/.github/actions/install-cuda-ubuntu@master
        env:
            cuda: 11.2.1_461
            GCC: 9
      - uses: ./.github/actions/install-protobuf-linux
      - name: Run tests on linux-x86_64
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
              nvcc --version
              mvn --version
              cmake --version
              protoc --version
              mvn  -Dlibnd4j.chip=cuda clean install -DskipTests

  android-x86_64:
      runs-on: ubuntu-18.04
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.8.0
          with:
            access_token: ${{ github.token }}
        - uses: nttld/setup-ndk@v1
          with:
            ndk-version: r18b
        - uses: actions/checkout@v2
        - uses: ./.github/actions/install-protobuf-linux
        - name: Build on linux-x86_64
          run: |
                curl -s http://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip -o android-ndk-r18b-linux-x86_64.zip && \
                unzip -q android-ndk-r18b-linux-x86_64.zip -d /opt && \
                rm -f android-ndk-r18b-linux-x86_64.zip
                echo "Verifying programs on path. Path is $PATH"
                echo "Path post update is $PATH. Maven is at `which mvn` cmake is at `which cmake` protoc is at `which protoc`"
                mvn --version
                cmake --version
                protoc --version
                mvn -Djavacpp.platform=android-x86_64 -libnd4j.platform=android-x86_64 -Ptest-nd4j-native -Dlibnd4j.chip=cpu clean install -DskipTests

  windows-x86_64:
      runs-on: windows-2019
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.8.0
          with:
            access_token: ${{ github.token }}
        - uses: actions/checkout@v2
        - uses: ./.github/actions/msys2-base-setup
        - name: Run tests
          shell: cmd
          run: |
            set MSYSTEM=MINGW64
            set "PATH=C:\msys64\usr\bin;%PATH%"
            mvn -Djavacpp.platform=windows-x86_64 -libnd4j.platform=windows-x86_64  -Dlibnd4j.chip=cpu clean install -DskipTests

  windows-x86_64-cuda-11-2:
    runs-on: windows-2019
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Use existing msys2 to setup environment
        uses: ./.github/actions/msys2-base-setup
      - name: Install cuda on windows
        uses: ./.github/actions/install-cuda-windows
      - uses: actions/checkout@v2
      - name: Run tests
        shell: cmd
        run: |
          set MSYSTEM=MINGW64
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set "PATH=C:\msys64\usr\bin;%PATH%"
          mvn -Djavacpp.platform=windows-x86_64 -libnd4j.platform=windows-x86_64 -Pcuda -Dlibnd4j.chip=cuda -Pcuda clean install -DskipTests

  mac-x86_64:
      runs-on: macos-10.15
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.8.0
          with:
            access_token: ${{ github.token }}
        - uses: actions/checkout@v2
        - name: Install and run tests
          shell: bash
          run: |
            mvn -Djavacpp.platform=macosx-x86_64 -libnd4j.platform=macosx-x86_64 -Dlibnd4j.chip=cpu clean install -DskipTests

