on:
  push:

jobs:
  linux-x86_64-cuda-11-2:
    runs-on: [self-hosted]
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Run cuda tests
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          export PATH="/opt/protobuf/bin:/usr/local/cuda-11.2/bin:$PATH"
          nvcc --version
          mvn --version
          cmake --version
          protoc --version
          bash ./change-cuda-versions.sh 11.2
          export OMP_NUM_THREADS=1
          mvn  -Ptestresources -pl ":deeplearning4j-modelimport,:deeplearning4j-core,:nd4j-cuda-11.2,:samediff-import,:libnd4j" -Dlibnd4j.compute="5.0 5.2 5.3 6.0 6.2 8.0"  -Ptest-nd4j-cuda  --also-make -Dlibnd4j.chip=cuda clean test

