on:
  push:
  pull_request:
jobs:
  linux-x86_64:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests on linux-x86_64
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
          M2_HOME: /opt/maven
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64/jre
        run: |

          echo "/opt/cmake/bin" >> $GITHUB_PATH
          echo "/opt/protobuf/bin" >> $GITHUB_PATH
          echo "/opt/maven/bin" >> $GITHUB_PATH
           apt-get -qqy update && \
                             apt-get -y --no-install-recommends install \
                                 wget \
                                 curl \
                                 unzip \
                                 apt-transport-https gnupg \
                                 ca-certificates \
                                 software-properties-common \
                                 git \
                                 build-essential \
                                 gnupg-agent \
                                 dirmngr \
                                 default-jre-headless \
                              openjdk-8-jdk-headless \
                                 libssl-dev \
                                  curl \
                                    ca-certificates \
                                 libgtk2.0-dev && \
                              apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
                              apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

           mkdir -p /opt/maven && \
           curl -fsSL http://apache.osuosl.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz | \
                             tar -xzC /opt/maven --strip-components=1

           curl -fsSL https://cmake.org/files/v3.19/cmake-3.19.0.tar.gz \
                         | tar xz && \
                         cd cmake-3.19.0 && \
                         ./configure --prefix=/opt/cmake && \
                         make -j2 && \
                         make install && \
                         cd .. && \
                         rm -r cmake-3.19.0

           curl -fsSL https://github.com/google/protobuf/releases/download/v3.5.1/protobuf-cpp-3.5.1.tar.gz \
                         | tar xz && \
                         cd protobuf-3.5.1 && \
                         ./configure --prefix=/opt/protobuf && \
                         make -j2 && \
                         make install && \
                         cd .. && \
                         rm -rf protobuf-3.5.1

           wget https://github.com/KonduitAI/dl4j-test-resources/archive/master.zip && unzip master.zip
          echo "Extracted test resources"
          echo "Verifying programs on path. Path is $PATH"
          export PATH="$PATH:/opt/cmake/bin:/opt/maven/bin:/opt/protobuf/bin"
          echo "Path post update is $PATH. Maven is at `which mvn` cmake is at `which cmake` protoc is at `which protoc`"
          mvn --version
          cmake --version
          protoc --version
          cd dl4j-test-resources-master && mvn clean
          mvn -Ptestresources -Ptest-nd4j-native -Dlibnd4j.chip=cpu clean test
