on:
  push:
jobs:
  linux-x86_64:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-protobuf-linux@actions
      - uses: ./.github/actions/download-dl4j-test-resources-linux@actions
      - name: Run tests on linux-x86_64
        shell: bash
        run: |

           wget https://github.com/KonduitAI/dl4j-test-resources/archive/master.zip && unzip master.zip
          echo "Extracted test resources"
          echo "Verifying programs on path. Path is $PATH"
          export PATH="/opt/cmake/bin:/opt/maven/bin:/opt/protobuf/bin:$PATH"
          echo "Path post update is $PATH. Maven is at `which mvn` cmake is at `which cmake` protoc is at `which protoc`"
          mvn --version
          cmake --version
          protoc --version
          cd dl4j-test-resources-master && mvn clean install -DskipTests && cd ..
          mvn -Ptestresources -Ptest-nd4j-native -Dlibnd4j.chip=cpu clean test

  android-x86_64:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-protobuf-linux@actions
      - uses: ./.github/actions/download-dl4j-test-resources-linux@actions
      - name: Run tests on linux-x86_64
        shell: bash
        run: |
          curl -s http://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip -o android-ndk-r18b-linux-x86_64.zip && \
          unzip -q android-ndk-r18b-linux-x86_64.zip -d /opt && \
          rm -f android-ndk-r18b-linux-x86_64.zip
          echo "Verifying programs on path. Path is $PATH"
          export PATH="/opt/cmake/bin:/opt/maven/bin:/opt/protobuf/bin:$PATH"
          echo "Path post update is $PATH. Maven is at `which mvn` cmake is at `which cmake` protoc is at `which protoc`"
          mvn --version
          cmake --version
          protoc --version
          mvn -Ptestresources-Djavacpp.platform=android-x86_64 -libnd4j.platform=android-x86_64 -Ptest-nd4j-native -Dlibnd4j.chip=cpu clean test


  windows-x86_64:
    runs-on: windows-2019
    steps:
      - uses: ./.github/actions/download-dl4j-test-resources-windows@actions
      - uses: ./.github/actions/msys2-base-setup@actions
      - uses: actions/checkout@v2
      - name: Run tests
        shell: cmd
        run: |
          set "PATH=C:\msys64\usr\bin;%PATH%"
          mvn -Ptestresources-Djavacpp.platform=windows-x86_64 -libnd4j.platform=windows-x86_64 -Ptest-nd4j-native -Dlibnd4j.chip=cpu clean test



  mac-x86_64:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/download-dl4j-test-resources-linux@actions
      - name: Install and run tests
        shell: bash
        run: |
          brew install unzip  ccache gcc swig autoconf-archive automake cmake libomp libtool libusb ant maven nasm xz pkg-config sdl gpg1 bison flex perl ragel binutils gradle gmp isl libmpc mpfr wget
          mvn -Ptestresources-Djavacpp.platform=windows-x86_64 -libnd4j.platform=windows-x86_64 -Ptest-nd4j-native -Dlibnd4j.chip=cpu clean test

