on:
  push:
jobs:
  linux-x86_64:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-protobuf-linux
      - uses: ./.github/actions/download-dl4j-test-resources-linux
      - name: Run tests on linux-x86_64
        shell: bash
        run: |
              mvn --version
              cmake --version
              protoc --version
              cd dl4j-test-resources-master && mvn clean install -DskipTests && cd ..
              mvn -Ptestresources -Ptest-nd4j-native -Dlibnd4j.chip=cpu clean test

  android-x86_64:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-protobuf-linux@actions
      - uses: ./.github/actions/download-dl4j-test-resources-linux
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21d
      - name: Run tests on linux-x86_64
        shell: bash
        env:
          ANDROID_NDK: /opt/hostedtoolcache/ndk/r21d/x64
        run: |
            mvn --version
            cmake --version
            protoc --version
            mvn -Ptestresources-Djavacpp.platform=android-x86_64 -libnd4j.platform=android-x86_64 -Ptest-nd4j-native -Dlibnd4j.chip=cpu clean test


  windows-x86_64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/download-dl4j-test-resources-windows
      - uses: ./.github/actions/msys2-base-setup
      - name: Run tests
        shell: cmd
        run: |
              set "PATH=C:\msys64\usr\bin;%PATH%"
              mvn -Ptestresources-Djavacpp.platform=windows-x86_64 -libnd4j.platform=windows-x86_64 -Ptest-nd4j-native -Dlibnd4j.chip=cpu clean test



  mac-x86_64:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/download-dl4j-test-resources-linux
      - name: Install and run tests
        shell: bash
        env:
          VERBOSE: 1
        run: |
            mvn -Ptestresources-Djavacpp.platform=windows-x86_64 -libnd4j.platform=windows-x86_64 -Ptest-nd4j-native -Dlibnd4j.chip=cpu clean test

