on:
  workflow_dispatch:
jobs:
  linux-x86_64:
    runs-on: [self-hosted]
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: ./.github/actions/download-dl4j-test-resources-linux
      - uses: actions/checkout@v2
      - name: Run cpu tests
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          export PATH="/opt/protobuf/bin:/usr/local/cuda-11.2/bin:$PATH"
          nvcc --version
          mvn --version
          cmake --version
          protoc --version
          export OMP_NUM_THREADS=1
          mvn   -DexcludedGroups="long-running-tests,large-resources, distributed-systems" -DskipTestResourceEnforcement=true -Ptestresources  -Pintegration-tests  -Pnd4j-tests-cpu   clean test -rf :deeplearning4j-core
          mvn -Dgroups="long-running-tests, large-resources, distributed-systems" -Ptestresources -Pnd4j-tests-cpu  -Dtest.offheap.size=14g -Dtest.heap.size=6g -Dsurefire.parallel.forcedTimeout=200 0Dsurefire.parallel.timeout=200  -Dsurefire.timeout=200 -Dsurefire.exitTimeout=200 test

