name: nd4j
on:
  push:
  pull_request:


jobs:
 linux-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - uses:  actions/checkout@v2
      - uses: ./.github/actions/build-dl4j-cpu
        env:
          M2_HOME: /opt/maven
          MAVEN_HOME: /opt/maven
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk
          PATH: /opt/cmake/bin:/opt/protobuf/bin:/opt/maven/bin:/usr/bin:/usr/lib/jvm/java-8-openjdk/bin
          JAVA_OPTS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
